### ISSUE TITLE
How to create a github repo by gh?

### ISSUE THREAD

**Issue by kang8** [kang8/kang8.github.io#23]
使用 [github cli](https://github.com/cli/cli) 创建 github 仓库非常方便，它是交互式的，体验非常好。在熟悉的情况下，比在浏览器中创建仓库快多了。

一般我会在现存的 git 仓库中直接执行 `gh repo create`，然后根据提示来创建仓库。

**Comment by Leaderzhangyi** [comment]
cy

**Comment by kang8** [comment]
@Leaderzhangyi 写完了
